import { readFile, writeFile } from 'fs/promises';
import { parse, stringify } from 'yaml';

export interface MorpheusConfig {
  project: string;
  template: 'ai-agent' | 'mcp-server' | 'website' | 'custom';
  provider: 'akash' | 'render' | 'filecoin';
  funding?: {
    wallet?: string;
    sourceToken: string;
    autoTopUp: boolean;
    threshold: number;
    duration?: string;
    split: {
      staking: number;
      compute: number;
    };
  };
  resources?: {
    tier?: 'small' | 'medium' | 'large' | 'custom';
    cpu?: number;
    memory?: string;
    storage?: string;
    gpu?: {
      units: number;
      model: string;
    };
  };
  runtime?: {
    image?: string;
    port?: number;
    framework?: 'nextjs' | 'express' | 'node';
  };
  env?: {
    variables?: Record<string, string>;
    secrets?: string[];
  };
}

export async function loadConfig(path: string): Promise<MorpheusConfig> {
  const content = await readFile(path, 'utf-8');
  const config = parse(content) as Partial<MorpheusConfig>;

  // Apply defaults
  return {
    project: config.project || 'unnamed',
    template: config.template || 'ai-agent',
    provider: config.provider || 'akash',
    resources: {
      tier: 'medium',
      cpu: 2,
      memory: '4Gi',
      storage: '10Gi',
      ...config.resources,
    },
    runtime: {
      port: 8000,
      ...config.runtime,
    },
    funding: {
      sourceToken: 'USDC',
      autoTopUp: true,
      threshold: 0.1,
      split: { staking: 0.6, compute: 0.4 },
      ...config.funding,
    },
    env: config.env,
  };
}

export async function saveConfig(path: string, config: MorpheusConfig): Promise<void> {
  const content = stringify(config, {
    indent: 2,
    lineWidth: 0,
  });
  await writeFile(path, content, 'utf-8');
}

interface GenerateConfigOptions {
  projectName: string;
  template: string;
  gpu?: { model: string; units: number };
  funding: {
    sourceToken: string;
    autoTopUp: boolean;
    threshold: number;
    duration?: string;
    split: { staking: number; compute: number };
  };
}

export function generateMorpheusConfig(options: GenerateConfigOptions): string {
  const config: MorpheusConfig = {
    project: options.projectName,
    template: options.template as MorpheusConfig['template'],
    provider: 'akash',
    funding: {
      sourceToken: options.funding.sourceToken,
      autoTopUp: options.funding.autoTopUp,
      threshold: options.funding.threshold,
      duration: options.funding.duration || '1y',
      split: options.funding.split,
    },
    resources: {
      tier: options.gpu ? 'large' : 'medium',
      cpu: options.gpu ? 4 : 2,
      memory: options.gpu ? '8Gi' : '4Gi',
      storage: '10Gi',
      ...(options.gpu && { gpu: options.gpu }),
    },
    runtime: {
      port: 8000,
    },
    env: {
      variables: {
        WORKFLOW_TARGET_WORLD: '@workflow/world-postgres',
        NODE_ENV: 'production',
      },
      secrets: ['OPENAI_API_KEY'],
    },
  };

  // Generate YAML with comments
  const yaml = `# Morpheus Project Configuration
# Generated by morpheus init

# Project Metadata
project: "${config.project}"
template: "${config.template}"
provider: "${config.provider}"

# Funding and Economic Strategy
funding:
  # wallet: "0x..." # Your Coinbase Smart Wallet address (auto-configured)
  sourceToken: "${config.funding!.sourceToken}"
  autoTopUp: ${config.funding!.autoTopUp}
  threshold: ${config.funding!.threshold}
  duration: "${config.funding!.duration}"  # 1y (1 year), 6m (6 months), 30d (30 days)
  split:
    staking: ${config.funding!.split.staking}  # 60% to MOR staking
    compute: ${config.funding!.split.compute}  # 40% to AKT compute

# Infrastructure Resource Requirements
resources:
  tier: "${config.resources!.tier}"
  cpu: ${config.resources!.cpu}
  memory: "${config.resources!.memory}"
  storage: "${config.resources!.storage}"${
    config.resources!.gpu
      ? `
  gpu:
    units: ${config.resources!.gpu.units}
    model: "${config.resources!.gpu.model}"`
      : ''
  }

# Application Runtime Settings
runtime:
  # image: "python:3.12" # Auto-detected or specify custom
  port: ${config.runtime!.port}
  # framework: "nextjs" # Auto-detected: nextjs, express, node

# Environment and Secret Management
env:
  variables:
    WORKFLOW_TARGET_WORLD: "@workflow/world-postgres"
    NODE_ENV: "production"

  # Sensitive keys (encrypted via Sealed Secrets before deployment)
  secrets:
    - OPENAI_API_KEY
    # - DATABASE_PASSWORD
`;

  return yaml;
}
